### ISSUE TITLE
Can't create a template

### ISSUE THREAD

**Issue by tonkonogov** [23maverick23/sublime-jekyll#71]
### Summary of issue
Can't create any issue. I call it via the command pallet and the context menu, then I enter title and description. After that nothing happened. A new tab with a template is not created, nor the file in the specified directory.

### System details

- System Platform - Linux Mint 17.3
- Sublime Version - b. 3114
- User or Project Settings - Project settings only

### Sublime console output
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1075, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
```

**Comment by 23maverick23** [comment]
Can you enable sublime-jekyll debug mode, restart Sublime, try to create a template, and then copy the FULL output from the ST console?

Also - can you confirm what version of sublime-jekyll you are using? The most recent is v3.1.1.

**Comment by tonkonogov** [comment]
The version is 3.1.1 according to the package control list. 

The output when I clicked the right button __once__ immediately after the start of sublime, the console was empty before the click:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 720, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 720, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 852, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 852, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 720, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 720, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 852, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 852, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1025, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1025, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1061, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1061, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1075, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1075, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1075, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 1075, in is_enabled
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
```

After specified steps (initiate creating, enter title and description) there is one more message:
```
Traceback (most recent call last):
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 974, in on_done_inner
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 570, in title_input
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 566, in path_string
  File "jekyll in /home/dmitry/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 284, in templates_path_string
NameError: global name 'templates_path' is not defined
```

**Comment by 23maverick23** [comment]
Got it - I see the issue. Thanks for reporting.

**Comment by 23maverick23** [comment]
I pushed an update that I think will solve your issue (I wasn't able to reproduce your exact error, but I can see where it might be happening).

Make sure you restart ST3 after installing the update and let me know if that resolves it. I don't have a Linux machine to test on so I'm assuming the platform doesn't affect my results (but you never know).

**Comment by tonkonogov** [comment]
Confirm, it works now, thanks for help.
